# Generated by Django 4.2 on 2025-01-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('historical', 'historical'), ('futuristic', 'futuristic'), ('mythical', 'mythical')], default='null', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_destinations.time_type')),
            ],
        ),
    ]
