# Generated by Django 4.2 on 2025-01-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'ntermediate'), ('Professinal', 'Professinal')], default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('last_name', models.CharField(max_length=220)),
                ('phone', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_travelers.skill')),
            ],
        ),
    ]
